import z from "zod";

export const AncestryNameEnum = z.enum([
  "human",
  "elf",
  "dwarf",
  "halfling",
  "gnome",
  "dragonborn",
  "tiefling",
  "aasimar",
  "goliath",
  "orc",
]);



export const ClassesIdEnum = z.enum(["paladin", "rogue", "wizard", "fighter", "barbarian", "monk", "cleric", "druid", "ranger", "sorcerer", "warlock", "bard"]);

export const LanguageEnum = z.enum([
  "common",
  "dwarvish",
  "elvish",
  "giant",
  "gnomish",
  "goblin",
  "halfling",
  "orc",
  "abyssal",
  "celestial",
  "draconic",
  "deepSpeech",
  "infernal",
  "primordial",
  "sylvan",
  "undercommon",
  "aquan",
  "auran",
  "ignan",
  "terran",
  "druidic",
  "thievesCant",
  "telepathy",
  "giantEagle",
  "giantOwl",
  "modron",
  "blinkDog",
  "sphinx",
  "gnoll",
  "grimlock",
  "kuoToa",
  "lizardfolk",
  "minotaur",
  "sahuagin",
  "troglodyte",
  "yeti",
  "worg",
  "aarakocra",
  "bullywug",
  "gith",
  "githyanki",
  "githzerai",
  "grung",
  "merfolk",
  "merrow",
  "myconid",
  "ogre",
  "quaggoth",
  "tabaxi",
  "thriKreen",
  "umberHulk",
  "vegepygmy",
  "yuanTi",
  "kobold",
  "eladrin",
  "quori",
  "slaad",
  "troll",
  "vampire",
  "willOWisp",
]);

export const AbilityScoreEnum = z.enum([
  "strength",
  "dexterity",
  "constitution",
  "intelligence",
  "wisdom",
  "charisma",
]);

export const SkillEnum = z.enum([
  "acrobatics",
  "animalHandling",
  "arcana",
  "athletics",
  "deception",
  "history",
  "insight",
  "intimidation",
  "investigation",
  "medicine",
  "nature",
  "perception",
  "performance",
  "persuasion",
  "religion",
  "sleightOfHand",
  "stealth",
  "survival",
]);

export const EnvironmentEnum = z.enum([
  "arctic",
  "coast",
  "desert",
  "forest",
  "grassland",
  "hill",
  "mountain",
  "swamp",
  "underdark",
  "underwater",
  "urban",
  "planar",
  "any",
  "feywild",
  "avernus",
  "theShadowfell",
  "theNineHells",
  "sigil",
  "mechanus",
  "theAbyss",
  "elysium",
  "pandemonium",
  "carceri",
  "arcadia",
  "theFeyCourt",
  "acheron",
  "theAstralSea",
  "jungle",
  "ruins",
  "volcano",
  "cavern",
  "wasteland",
  "savanna",
  "tundra",
  "steppe",
  "marsh",
  "reef",
  "island",
  "temple",
  "graveyard",
  "castle",
  "labyrinth",
  "mine",
  "ship",
  "sky",
  "dreamscape",
  "etherealPlane",
  "shadowPlane",
  "elementalPlaneFire",
  "elementalPlaneWater",
  "elementalPlaneEarth",
  "elementalPlaneAir",
  "limbo",
  "mountCelestia",
  "baator",
  "gehenna",
  "ysgard",
  "beastlands",
  "bytopia",
  "outlands",
  "primeMaterial",
]);

export const AlignmentEnum = z.enum([
  "lawfulGood",
  "neutralGood",
  "chaoticGood",
  "lawfulNeutral",
  "trueNeutral",
  "chaoticNeutral",
  "lawfulEvil",
  "neutralEvil",
  "chaoticEvil",
  "unaligned",
]);

export const VisionTypeEnum = z.enum([
  "darkvision",
  "blindsight",
  "tremorsense",
  "truesight",
]);

export const FeatCategoryEnum = z.enum(["general", "fightingStyle", "origin", "epicBoon"]);

export const DispositionEnum = z.enum(["friendly", "neutral", "hostile"]);
