CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL,
  password_hash VARCHAR(120) NOT NULL,
  role VARCHAR(20) NOT NULL,
  avatar_url CLOB,
  CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  token_hash VARCHAR(128) NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
  CONSTRAINT fk_refresh_tokens_user
    FOREIGN KEY (user_id)
    REFERENCES users (id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id
  ON refresh_tokens (user_id);

CREATE TABLE IF NOT EXISTS game_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  description VARCHAR(1000),
  join_code VARCHAR(12) NOT NULL,
  max_players INTEGER NOT NULL,
  current_players INTEGER NOT NULL,
  status VARCHAR(20) NOT NULL,
  owner_id BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT uk_game_sessions_join_code UNIQUE (join_code),
  CONSTRAINT fk_game_sessions_owner
    FOREIGN KEY (owner_id)
    REFERENCES users (id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_game_sessions_status_created
  ON game_sessions (status, created_at);

CREATE INDEX IF NOT EXISTS idx_game_sessions_owner_id
  ON game_sessions (owner_id);

CREATE TABLE IF NOT EXISTS game_session_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_session_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT uk_game_session_member UNIQUE (game_session_id, user_id),
  CONSTRAINT fk_game_session_members_game
    FOREIGN KEY (game_session_id)
    REFERENCES game_sessions (id)
    ON DELETE CASCADE,
  CONSTRAINT fk_game_session_members_user
    FOREIGN KEY (user_id)
    REFERENCES users (id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_game_session_members_game
  ON game_session_members (game_session_id);

CREATE INDEX IF NOT EXISTS idx_game_session_members_user
  ON game_session_members (user_id);

CREATE TABLE IF NOT EXISTS game_join_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_session_id BIGINT NOT NULL,
  requester_id BIGINT NOT NULL,
  status VARCHAR(20) NOT NULL,
  requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
  reviewed_at TIMESTAMP WITH TIME ZONE,
  reviewed_by_user_id BIGINT,
  CONSTRAINT fk_game_join_requests_game
    FOREIGN KEY (game_session_id)
    REFERENCES game_sessions (id)
    ON DELETE CASCADE,
  CONSTRAINT fk_game_join_requests_requester
    FOREIGN KEY (requester_id)
    REFERENCES users (id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_game_join_requests_session_status
  ON game_join_requests (game_session_id, status, requested_at);

CREATE INDEX IF NOT EXISTS idx_game_join_requests_requester
  ON game_join_requests (requester_id);
