CREATE TABLE IF NOT EXISTS game_session_state (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_session_id BIGINT NOT NULL UNIQUE,
  version BIGINT NOT NULL DEFAULT 0,
  state_json CLOB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_game_session_state_game
    FOREIGN KEY (game_session_id)
    REFERENCES game_sessions (id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_game_session_state_game
  ON game_session_state (game_session_id);
