CREATE TABLE IF NOT EXISTS game_session_revocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_session_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  revoked_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT uk_game_session_revocation UNIQUE (game_session_id, user_id),
  CONSTRAINT fk_game_session_revocations_game
    FOREIGN KEY (game_session_id)
    REFERENCES game_sessions (id)
    ON DELETE CASCADE,
  CONSTRAINT fk_game_session_revocations_user
    FOREIGN KEY (user_id)
    REFERENCES users (id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_game_session_revocations_game
  ON game_session_revocations (game_session_id);

CREATE INDEX IF NOT EXISTS idx_game_session_revocations_user
  ON game_session_revocations (user_id);
