CREATE TABLE IF NOT EXISTS game_session_revoked_emails (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_session_id BIGINT NOT NULL,
  email VARCHAR(180) NOT NULL,
  revoked_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT uk_game_session_revoked_email UNIQUE (game_session_id, email),
  CONSTRAINT fk_game_session_revoked_emails_game
    FOREIGN KEY (game_session_id)
    REFERENCES game_sessions (id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_game_session_revoked_emails_game
  ON game_session_revoked_emails (game_session_id);

CREATE INDEX IF NOT EXISTS idx_game_session_revoked_emails_email
  ON game_session_revoked_emails (email);
